FROM node:20-alpine AS build

WORKDIR /app/frontend

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./
RUN npm run build

FROM node:20-alpine

WORKDIR /app/frontend

RUN npm install -g serve

COPY --from=build /app/frontend/build ./build

EXPOSE 80

CMD ["serve", "-s", "build", "-l", "80"]
