services:
  frontend:
    # Build frontend tu source code local voi Node server runtime.
    build:
      context: ../proshop_mern
      dockerfile: frontend/Dockerfile.node
    container_name: frontend-local
    networks:
      - observability
